// This file is auto generated. See scripts/generator.ts
import { License } from "./types.ts";
export const BSL_1_0: License = {
  "title": "Boost Software License 1.0",
  "spdx-id": "BSL-1.0",
  "hidden": false,
  "description":
    "A simple permissive license only requiring preservation of copyright and license notices for source (and not binary) distribution. Licensed works, modifications, and larger works may be distributed under different terms and without source code.",
  "how":
    "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file.",
  "note":
    "Boost recommends taking the additional step of adding a boilerplate notice to the top of each file. The boilerplate can be found at the [Boost Software License FAQ](https://www.boost.org/users/license.html#FAQ).",
  "using": [
    {
      "Boost": "https://github.com/boostorg/boost/blob/master/LICENSE_1_0.txt",
    },
    {
      "Catch2": "https://github.com/catchorg/Catch2/blob/master/LICENSE.txt",
    },
    {
      "DMD": "https://github.com/dlang/dmd/blob/master/LICENSE.txt",
    },
  ],
  "permissions": [
    "commercial-use",
    "modifications",
    "distribution",
    "private-use",
  ],
  "conditions": [
    "include-copyright--source",
  ],
  "limitations": [
    "liability",
    "warranty",
  ],
  "text":
    '\n\nBoost Software License - Version 1.0 - August 17th, 2003\n\nPermission is hereby granted, free of charge, to any person or organization\nobtaining a copy of the software and accompanying documentation covered by\nthis license (the "Software") to use, reproduce, display, distribute,\nexecute, and transmit the Software, and to prepare derivative works of the\nSoftware, and to permit third-parties to whom the Software is furnished to\ndo so, all subject to the following:\n\nThe copyright notices in the Software and this entire statement, including\nthe above license grant, this restriction and the following disclaimer,\nmust be included in all copies of the Software, in whole or in part, and\nall derivative works of the Software, unless such copies or derivative\nworks are solely in the form of machine-executable object code generated by\na source language processor.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT\nSHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE\nFOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,\nARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER\nDEALINGS IN THE SOFTWARE.\n',
};
